version: '3.9'

services:
  
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    environment:
      - PORT=${PORT}
    depends_on:
      - blue_env
      - green_env
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - app-network

  blue_env:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT}" 
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    networks:
      - app-network

  green_env:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT}" 
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    networks:
      - app-network

  alert_watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    environment:
      - LOG_FILE_PATH=/var/log/nginx/access.log
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_PERIOD=${ALERT_COOLDOWN_PERIOD}
    depends_on: 
      - nginx
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs:
